name: fluttering_ermine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  provider: ^6.1.2
  shared_preferences: ^2.3.4
  livekit_client: ^2.7.0
  connectivity_plus_linux_portal:
    git:
      url: https://github.com/EchoEllet/dart-packages.git
      path: packages/connectivity_plus_linux_portal
  file_picker: ^11.0.2
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0
  web: ^1.1.1

dependency_overrides:
  flutter_webrtc:
    git:
      url: https://github.com/Noobidoo/flutter-webrtc.git
      ref: feature/windows-loopback-audio

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
      - assets/fluttering_ermine.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/fluttering_ermine.png"
  web:
    generate: true
    image_path: "assets/fluttering_ermine.png"
  windows:
    generate: true
    image_path: "assets/fluttering_ermine.png"