name: fluttering_ermine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  web_socket_channel: ^3.0.1
  provider: ^6.1.2
  shared_preferences: ^2.5.5
  livekit_client: ^2.7.0
  flutter_webrtc: ^1.4.0
  connectivity_plus_linux_portal:
    git:
      url: https://github.com/EchoEllet/dart-packages.git
      path: packages/connectivity_plus_linux_portal
  file_picker: ^11.0.2
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0
  web: ^1.1.1
  image: ^4.8.0
  deepfilter_livekit:
    git:
      url: https://github.com/Noobidoo/deepfilter_livekit
      ref: v0.1.4

dependency_overrides:
  deepfilter_livekit:
    path: ../deepfilter_livekit
  permission_handler_windows:
    git:
      url: https://github.com/localsend/permission_handler_windows_noop.git
  flutter_webrtc:
    git:
      url: https://github.com/flutter-webrtc/flutter-webrtc.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  test: ^1.25.0
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1
  mocktail: ^1.0.0
  shared_preferences_platform_interface: ^2.4.2

flutter:
  uses-material-design: true
  assets:
      - assets/fluttering_ermine.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/fluttering_ermine.png"
  web:
    generate: true
    image_path: "assets/fluttering_ermine.png"
  windows:
    generate: true
    image_path: "assets/fluttering_ermine.png"